site_name: DoorHardware - CT
nav:
  - General: index.md
  - Home: home.md
  - Category: category.md
  - Product: product.md
  - Static: static.md
  - Contact Us: contact.md
  - Mega Menu: menu.md
  - Footer: footer.md
theme: readthedocs
extra_css:
  - style.css
